// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      this.playerCheck21();
      return this.listeners();
    };

    App.prototype.playerCheck21 = function() {
      var allLose, i, length, player, playerScore, _i, _len;
      player = this.get('playerHand');
      playerScore = player.scores();
      console.log(playerScore);
      allLose = [];
      length = playerScore.length;
      for (_i = 0, _len = playerScore.length; _i < _len; _i++) {
        i = playerScore[_i];
        if (i > 21) {
          allLose.push(true);
        } else if (i === 21) {
          this.youWin(playerScore);
        } else {
          allLose.push(false);
        }
      }
      console.log(allLose);
      allLose = _.reduce(allLose, function(accu, value) {
        return accu && value;
      });
      if (allLose === true) {
        return this.youLose(playerScore);
      }
    };

    App.prototype.listeners = function() {
      var _this = this;
      this.get('playerHand').on('playerHit', function() {
        _this.playerCheck21();
        return void 0;
      });
      return void 0;
    };

    App.prototype.youLose = function(score) {
      $('body').text('You Lose!!!!!!!').append($('<button class="playAgain">Play again</button>'));
      return $('.playAgain').on('click', function() {
        $('body').text('');
        return new AppView({
          model: new App()
        }).$el.appendTo('body');
      });
    };

    App.prototype.youWin = function(score) {
      $('body').text('You Win!!!!!!!').append($('<button class="playAgain">Play again</button>'));
      return $('.playAgain').on('click', function() {
        $('body').text('');
        return new AppView({
          model: new App()
        }).$el.appendTo('body');
      });
    };

    return App;

  })(Backbone.Model);

}).call(this);

/*
//@ sourceMappingURL=App.map
*/
